### ISSUE TITLE
Plan out network deployment @ 190/200

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/mesh-deployment#11]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Have a clear map of first super node 

...

## To Do

- [x] Decide on location of antennas
- [x] Decide on layer 2 topology
- [x] Lab test it #1 
- [x] Decide on IP organization #8
