### ISSUE TITLE
Document 

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/mesh-deployment#32]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

...

## To Do
- [ ] #15 Select Router
  - [ ] #22 Router X As Router
  - [ ] #12 - Espresso bin As Router
- [ ] #17 - Nema Cabinate
- [ ] #20 POE Switch
- [ ] #5 Super Node 1 Hardware
- [ ] ...

**Comment by makeworld-the-better-one** [comment]
#54 might supersede this issue.

**Comment by darkdrgn2k** [comment]
Discuss scope of issues

**Comment by makeworld-the-better-one** [comment]
Done today, this issue will stay open. I've updated it to include any new issues I found previously.

**Comment by makeworld-the-better-one** [comment]
Overall network topology images: [benhylau drawing](https://github.com/tomeshnet/toronto-community-network/issues/54#issuecomment-668482076) and [DD2k diagram](https://github.com/tomeshnet/toronto-community-network/issues/54#issuecomment-669651527)

**Comment by benhylau** [comment]
I think a quick way to get stuff transferred is to agree on the "chapters" index and then transfer content on there, then assign one person to go thru all of it, make everything consistent and pretty.

**Comment by makeworld-the-better-one** [comment]
Yeah, starting to create a draft/template of all the sections sounds like the right idea. Can this be done here?

**Comment by benhylau** [comment]
I think it can be in this, and check off sections as they get merged.

**Comment by makeworld-the-better-one** [comment]
## Docs chapters

Please edit this comment to add sections. Use of subchapters is encouraged.

- [ ] Introduction - explains the Toronto Community Network, and what the docs/book is for
- [ ] Get Involved - #35 Contributor onboarding
- [ ] Branding Guideline
	- [ ] #30 Toronto Mesh naming
	- [ ] Logo, colour schemes, etc
- [ ] Hardware
	- Add subchapters for hardware in use, recommendations, pros and cons, etc
- [ ] Testing data
	- [ ] #34 Supernode 1 field testing
- [ ] Supernodes
	- [ ] #29 200 Woolner
- [ ] Exit nodes - idk what to put here exactly - #6 

## Questions
- Should the docs have sections explaining what the network is in depth, with an FAQ, etc? Or should that be on tomesh.net?

**Comment by darkdrgn2k** [comment]
I would suggest putting the above comment as part of the first one.

that way we don't have to dig for it!

**Comment by makeworld-the-better-one** [comment]
Done, thanks. I've left my question though.

**Comment by darkdrgn2k** [comment]
#34 Supernode 1 field testing

This seems like more of a tomesh/documents write up about what we did (the event) and just the results in the docs.

**Comment by makeworld-the-better-one** [comment]
I think it definitely depends on the nature of the write up. It'd be nice to have some info in the docs on how it was done, like with tips or important info. But any sort of narrative would be better for a blog post or document.

**Comment by darkdrgn2k** [comment]
Discussed in one of the meetings

Docs.tomesh.net will be a "manual" while the Journal/Blog/Event recap will be in some other location (blog maybe, or docs)
