### ISSUE TITLE
First Toronto Exit Node

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/mesh-deployment#33]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #6
📅 **Due date:** N/A  
🎯 **Success criteria:** Establish Toronto local exit node.

...

## To Do

- [ ] Cisco exit node
  - [x] Contact Beanfield #10 
  - [ ] Get circut donated/paid
  - [ ] Get circuit installed @ cisco?
  - [ ] Rack and Stack Servers
  - [ ] Install Debian running Babeld and accept L2TP tunnels

**Comment by rwhiteside90** [comment]
What is the plan for servers? I have some Dell R715s I can donate as mentioned with 128GB of memory and I believe 6x 300GB 10K SAS drives.  I would suggest a hypervisor on these instead of just installing Debian bare metal.  

I also have some older Cisco switches I can donate as well, will need to verify what I have.
