### ISSUE TITLE
Get hardware for deployment - Node 1

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/mesh-deployment#5]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Hardware ready for deployment 

...

## To Do

- [x] Router
  - [x] Select Device #15
  - [x] Order Device
  - [x] Receive Device
  - [x] Configure Device
- [ ] ~~POE Switch #18~~ Router- X-SFP doubles as POE Switch 
- [X] Sectors
  - [x] Ubiquity AP120 AC
  - [x] ~~Order Device~~ Confirm with Pedor
  - [x] Receive Device
  - [x] Configure Device
- [x] ~~UPS~~ (~~Cant do it in a NEMA~~ wont do)
- [x] ~~Nema Cabinet~~ (No need for node 1) #17
